services:
  - type: web
    name: zylh_cor_ewsd_project
    plan: free 
    runtime: php  
    buildCommand: composer install
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:I5vzyMM/X/WCcg3YMUABx9s3p1FMQHepuzhv/sPXoE0=
      - key: APP_URL
        value: https://production_laravel.onrender.com